// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Banyan.Entities.Models;

public partial class AccountStatus
{
    public byte? Id { get; set; }

    public string Name { get; set; }

    public bool? IsActive { get; set; }
}