// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Banyan.Entities.Models;

public partial class AddressBook
{
    public int Id { get; set; }

    public string AddressLine1 { get; set; }

    public string AddressLine2 { get; set; }

    public string AddressLine1Bangla { get; set; }

    public int? DivisionId { get; set; }

    public int? DistrictId { get; set; }

    public int? UpazilaId { get; set; }

    public int? UnionId { get; set; }

    public int? MauzaId { get; set; }

    public int? VillageId { get; set; }

    public int? PostOfficeId { get; set; }

    public string TelephoneNo { get; set; }

    public string MobileNo { get; set; }

    public string Email { get; set; }

    public virtual ICollection<Employee> EmployeePermanentAddress { get; set; } = new List<Employee>();

    public virtual ICollection<Employee> EmployeePresentAddress { get; set; } = new List<Employee>();

    public virtual ICollection<IndividualDetails> IndividualDetailsPermanentAddress { get; set; } = new List<IndividualDetails>();

    public virtual ICollection<IndividualDetails> IndividualDetailsPresentAddress { get; set; } = new List<IndividualDetails>();

    public virtual ICollection<InstitutionDetails> InstitutionDetails { get; set; } = new List<InstitutionDetails>();

    public virtual Union Union { get; set; }
}