// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Banyan.Entities.Models;

public partial class Client
{
    public int Id { get; set; }

    public bool? IsMember { get; set; }

    public bool? IsInstitution { get; set; }

    public DateOnly? SavingsOpeningDate { get; set; }

    public int? SavingsNo { get; set; }

    public decimal? SavingsBalance { get; set; }

    public int? IntroducerMemNo { get; set; }

    public byte? ClientStatusId { get; set; }

    public DateOnly? ClientStatusEffectiveDate { get; set; }

    public DateOnly? IdissueDate { get; set; }

    public int? UserId { get; set; }

    public DateTime? SetDate { get; set; }

    public bool? IsVerified { get; set; }

    public int? VerifiedBy { get; set; }

    public DateTime? VerifiedDate { get; set; }

    public DateTime? ClientHistoryDate { get; set; }

    public virtual ClientStatus ClientStatus { get; set; }

    public virtual IndividualDetails IndividualDetails { get; set; }

    public virtual InstitutionDetails InstitutionDetails { get; set; }
}