// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Banyan.Entities.Models;

public partial class Country
{
    public int Id { get; set; }

    public string CountryName { get; set; }

    public string Iso2 { get; set; }

    public string Iso3 { get; set; }

    public string HrCode { get; set; }

    public string Nationality { get; set; }

    public virtual ICollection<Division> Division { get; set; } = new List<Division>();
}