// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Banyan.Entities.Models;

public partial class District
{
    public int? CountryId { get; set; }

    public int? DivisionId { get; set; }

    public int Id { get; set; }

    public string DivisionCode { get; set; }

    public string DistrictCode { get; set; }

    public string HrDivisionId { get; set; }

    public string HrDistrictId { get; set; }

    public string AccountDistrictId { get; set; }

    public string DistrictName { get; set; }

    public string DivisionName { get; set; }

    public double? Lat { get; set; }

    public double? Long { get; set; }

    public string AllInOne { get; set; }

    public string Status { get; set; }

    public string UserId { get; set; }

    public virtual Division Division { get; set; }

    public virtual ICollection<IndividualDetails> IndividualDetails { get; set; } = new List<IndividualDetails>();

    public virtual ICollection<Upazila> Upazila { get; set; } = new List<Upazila>();
}