// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Banyan.Entities.Models;

public partial class Division
{
    public int? CountryId { get; set; }

    public int Id { get; set; }

    public string DivisionCode { get; set; }

    public string HrDivisionId { get; set; }

    public string DivisionName { get; set; }

    public double? Lat { get; set; }

    public double? Long { get; set; }

    public string Status { get; set; }

    public virtual Country Country { get; set; }

    public virtual ICollection<District> District { get; set; } = new List<District>();
}