// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Banyan.Entities.Models;

public partial class EmployeeHistory
{
    public DateTime HistoryDate { get; set; }

    public int? HistoryBy { get; set; }

    public bool? IsDeleted { get; set; }

    public int? Id { get; set; }

    public string Pin { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public DateOnly? JoiningDate { get; set; }

    public DateOnly? SeparationDate { get; set; }

    public int? PresentAddressId { get; set; }

    public int? PermanentAddressId { get; set; }

    public byte? JobTypeId { get; set; }

    public byte? JobStatusId { get; set; }

    public byte? DepartmentId { get; set; }

    public byte? DesignationId { get; set; }

    public byte? JobGradeId { get; set; }

    public int? ManagerId { get; set; }

    public int? UserId { get; set; }

    public DateTime? SetDate { get; set; }

    public bool? IsVerified { get; set; }

    public int? VerifiedBy { get; set; }

    public DateTime? VerifiedDate { get; set; }

    public DateTime? EmployeeHistoryDate { get; set; }
}