// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Banyan.Entities.Models
{
    public partial class findResult
    {
        [StringLength(128)]
        public string Schema { get; set; }
        [StringLength(128)]
        public string Name { get; set; }
        public string Type { get; set; }
        public long? Rows { get; set; }
    }
}
