// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Banyan.Entities.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Banyan.Entities.Models
{
    public partial interface IMCCCULContextProcedures
    {
        Task<int> AddressBookInsertAsync(byte[] token, string secretKey, string addressLine1, string addressLine2, string addressLine1Bangla, int? divisionID, int? districtID, int? upazilaID, int? unionID, int? mauzaID, int? villageID, int? postOfficeID, string telephoneNo, string mobileNo, string email, OutputParameter<int?> iD, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> AddressBookUpdateAsync(byte[] token, string secretKey, int? iD, string addressLine1, string addressLine2, string addressLine1Bangla, int? divisionID, int? districtID, int? upazilaID, int? unionID, int? mauzaID, int? villageID, int? postOfficeID, string telephoneNo, string mobileNo, string email, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> AuthenticateUserAsync(int? employeeID, string userName, string password, string secretKey, OutputParameter<byte[]> token, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> CreateEmployeeAsync(byte[] token, string secretKey, string pIN, string firstName, string lastName, string email, string phone, DateOnly? joiningDate, int? presentAddressID, int? permanentAddressID, byte? jobTypeID, byte? jobStatusID, byte? departmentID, byte? designationID, byte? jobGradeID, int? managerID, OutputParameter<int?> iD, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> CreateIndividualClientAsync(byte[] token, string secretKey, bool? isMember, bool? isInstitution, DateOnly? savingsOpeningDate, int? savingsNo, decimal? savingsBalance, int? introducerMemNo, byte? clientStatusID, DateOnly? clientStatusEffectiveDate, DateOnly? iDIssueDate, DateTime? setDate, string clientName, string clientLastName, string clientNameBangla, string fatherName, string fatherNameBang, int? fatherClientNo, string motherName, string motherNameBang, int? motherClientNo, string spouseName, string spouseNameBang, int? spouseClientNo, byte? professionID, string gender, string religion, string maritalStatus, string bloodGroup, DateTime? dateOfBirth, int? presentAddressID, int? permanentAddressID, string employerName, int? employerAddressID, string nID, string passportNo, string tIN, int? birthPlaceDistrictID, string educationalQualification, string birthCertificateNo, OutputParameter<int?> iD, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> CreateInstitutionalClientAsync(byte[] token, string secretKey, bool? isMember, bool? isInstitution, DateOnly? savingsOpeningDate, int? savingsNo, decimal? savingsBalance, int? introducerMemNo, byte? clientStatusID, DateOnly? clientStatusEffectiveDate, DateOnly? iDIssueDate, DateTime? setDate, string clientName, string clientNameBangla, string signatoryName1, string signatoryName2, int? addressID, string tradelicenseNo, string regNo, OutputParameter<int?> iD, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> CreateMemberAsync(byte[] token, string secretKey, int? clientID, int? memberNo, DateOnly? membershipDate, decimal? shareBalance, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> DecryptTokenAsync(byte[] token, string secretKey, OutputParameter<int?> iD, OutputParameter<byte?> roleID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> DeleteClientAsync(byte[] token, string secretKey, int? iD, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> DeleteEmployeeAsync(byte[] token, string secretKey, int? iD, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<findResult>> findAsync(string name, string type, string schema, long? rowsMin, long? rowsMax, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<lookupResult>> lookupAsync(string @object, string q1, string q2, string q3, string q4, string q5, string q6, string q7, string q8, string q9, string q10, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<showResult>> showAsync(string @object, string query, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> UpdateClientAsync(byte[] token, string secretKey, int? iD, bool? isMember, bool? isInstitution, DateOnly? savingsOpeningDate, int? savingsNo, decimal? savingsBalance, int? introducerMemNo, byte? clientStatusID, DateOnly? clientStatusEffectiveDate, DateOnly? iDIssueDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> UpdateEmployeeAsync(byte[] token, string secretKey, int? iD, string firstName, string lastName, string email, string phone, DateOnly? joiningDate, DateOnly? separationDate, int? presentAddressID, int? permanentAddressID, byte? jobTypeID, byte? jobStatusID, byte? departmentID, byte? designationID, byte? jobGradeID, int? managerID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> VerifyClientAsync(byte[] token, string secretKey, int? iD, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> VerifyEmployeeAsync(byte[] token, string secretKey, int? iD, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
