// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Banyan.Entities.Models;

public partial class IndividualDetails
{
    public int ClientId { get; set; }

    public string ClientName { get; set; }

    public string ClientLastName { get; set; }

    public string ClientNameBangla { get; set; }

    public string FatherName { get; set; }

    public string FatherNameBang { get; set; }

    public int? FatherClientNo { get; set; }

    public string MotherName { get; set; }

    public string MotherNameBang { get; set; }

    public int? MotherClientNo { get; set; }

    public string SpouseName { get; set; }

    public string SpouseNameBang { get; set; }

    public int? SpouseClientNo { get; set; }

    public byte? ProfessionId { get; set; }

    public string Gender { get; set; }

    public string Religion { get; set; }

    public string MaritalStatus { get; set; }

    public string BloodGroup { get; set; }

    public DateTime? DateOfBirth { get; set; }

    public int? PresentAddressId { get; set; }

    public int? PermanentAddressId { get; set; }

    public string EmployerName { get; set; }

    public int? EmployerAddressId { get; set; }

    public string Nid { get; set; }

    public string PassportNo { get; set; }

    public string Tin { get; set; }

    public int? BirthPlaceDistrictId { get; set; }

    public string EducationalQualification { get; set; }

    public string BirthCertificateNo { get; set; }

    public virtual District BirthPlaceDistrict { get; set; }

    public virtual Client Client { get; set; }

    public virtual IndividualDetails FatherClientNoNavigation { get; set; }

    public virtual ICollection<IndividualDetails> InverseFatherClientNoNavigation { get; set; } = new List<IndividualDetails>();

    public virtual ICollection<IndividualDetails> InverseMotherClientNoNavigation { get; set; } = new List<IndividualDetails>();

    public virtual ICollection<IndividualDetails> InverseSpouseClientNoNavigation { get; set; } = new List<IndividualDetails>();

    public virtual MemberProfile MemberProfile { get; set; }

    public virtual IndividualDetails MotherClientNoNavigation { get; set; }

    public virtual AddressBook PermanentAddress { get; set; }

    public virtual AddressBook PresentAddress { get; set; }

    public virtual Profession Profession { get; set; }

    public virtual IndividualDetails SpouseClientNoNavigation { get; set; }
}