// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Banyan.Entities.Models;

public partial class InstitutionDetails
{
    public int ClientId { get; set; }

    public string ClientName { get; set; }

    public string ClientNameBangla { get; set; }

    public string SignatoryName1 { get; set; }

    public string SignatoryName2 { get; set; }

    public int? AddressId { get; set; }

    public string TradelicenseNo { get; set; }

    public string RegNo { get; set; }

    public virtual AddressBook Address { get; set; }

    public virtual Client Client { get; set; }
}