// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Banyan.Entities.Models;

public partial class JobGrade
{
    public byte Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public byte? Rank { get; set; }

    public byte? GradeBandId { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<Employee> Employee { get; set; } = new List<Employee>();

    public virtual GradeBand GradeBand { get; set; }
}