// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Banyan.Entities.Models;

public partial class Mauza
{
    public int? UnionId { get; set; }

    public int Id { get; set; }

    public int? DivisionId { get; set; }

    public int? DistrictId { get; set; }

    public int? UpazilaId { get; set; }

    public int? PaurashavaAreaId { get; set; }

    public string DivisionCode { get; set; }

    public string DistrictCode { get; set; }

    public string UpazilaCode { get; set; }

    public string PsaCode { get; set; }

    public string UnionCode { get; set; }

    public string MauzaCode { get; set; }

    public string DivisionName { get; set; }

    public string DistrictName { get; set; }

    public string UpazilaName { get; set; }

    public string PaurashavaName { get; set; }

    public string UnionName { get; set; }

    public string MauzaName { get; set; }

    public string AllInOne { get; set; }

    public int? Rmo { get; set; }

    public string Status { get; set; }

    public virtual Union Union { get; set; }

    public virtual ICollection<Village> Village { get; set; } = new List<Village>();
}