// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Banyan.Entities.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Banyan.Entities.Models
{
    public partial class MCCCULContext
    {
        private IMCCCULContextProcedures _procedures;

        public virtual IMCCCULContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new MCCCULContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IMCCCULContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class MCCCULContextProcedures : IMCCCULContextProcedures
    {
        private readonly MCCCULContext _context;

        public MCCCULContextProcedures(MCCCULContext context)
        {
            _context = context;
        }

        public virtual async Task<int> AddressBookInsertAsync(byte[] token, string secretKey, string addressLine1, string addressLine2, string addressLine1Bangla, int? divisionID, int? districtID, int? upazilaID, int? unionID, int? mauzaID, int? villageID, int? postOfficeID, string telephoneNo, string mobileNo, string email, OutputParameter<int?> iD, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterID = new SqlParameter
            {
                ParameterName = "ID",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = iD?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Token",
                    Size = 256,
                    Value = token ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarBinary,
                },
                new SqlParameter
                {
                    ParameterName = "SecretKey",
                    Size = 100,
                    Value = secretKey ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "AddressLine1",
                    Size = 100,
                    Value = addressLine1 ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "AddressLine2",
                    Size = 100,
                    Value = addressLine2 ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "AddressLine1Bangla",
                    Size = 100,
                    Value = addressLine1Bangla ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "DivisionID",
                    Value = divisionID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "DistrictID",
                    Value = districtID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "UpazilaID",
                    Value = upazilaID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "UnionID",
                    Value = unionID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "MauzaID",
                    Value = mauzaID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "VillageID",
                    Value = villageID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "PostOfficeID",
                    Value = postOfficeID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "TelephoneNo",
                    Size = 15,
                    Value = telephoneNo ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "MobileNo",
                    Size = 15,
                    Value = mobileNo ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Email",
                    Size = 30,
                    Value = email ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                parameterID,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [ad].[AddressBookInsert] @Token = @Token, @SecretKey = @SecretKey, @AddressLine1 = @AddressLine1, @AddressLine2 = @AddressLine2, @AddressLine1Bangla = @AddressLine1Bangla, @DivisionID = @DivisionID, @DistrictID = @DistrictID, @UpazilaID = @UpazilaID, @UnionID = @UnionID, @MauzaID = @MauzaID, @VillageID = @VillageID, @PostOfficeID = @PostOfficeID, @TelephoneNo = @TelephoneNo, @MobileNo = @MobileNo, @Email = @Email, @ID = @ID OUTPUT", sqlParameters, cancellationToken);

            iD?.SetValue(parameterID.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> AddressBookUpdateAsync(byte[] token, string secretKey, int? iD, string addressLine1, string addressLine2, string addressLine1Bangla, int? divisionID, int? districtID, int? upazilaID, int? unionID, int? mauzaID, int? villageID, int? postOfficeID, string telephoneNo, string mobileNo, string email, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Token",
                    Size = 256,
                    Value = token ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarBinary,
                },
                new SqlParameter
                {
                    ParameterName = "SecretKey",
                    Size = 100,
                    Value = secretKey ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "ID",
                    Value = iD ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "AddressLine1",
                    Size = 100,
                    Value = addressLine1 ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "AddressLine2",
                    Size = 100,
                    Value = addressLine2 ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "AddressLine1Bangla",
                    Size = 100,
                    Value = addressLine1Bangla ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "DivisionID",
                    Value = divisionID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "DistrictID",
                    Value = districtID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "UpazilaID",
                    Value = upazilaID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "UnionID",
                    Value = unionID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "MauzaID",
                    Value = mauzaID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "VillageID",
                    Value = villageID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "PostOfficeID",
                    Value = postOfficeID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "TelephoneNo",
                    Size = 15,
                    Value = telephoneNo ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "MobileNo",
                    Size = 15,
                    Value = mobileNo ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Email",
                    Size = 30,
                    Value = email ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [ad].[AddressBookUpdate] @Token = @Token, @SecretKey = @SecretKey, @ID = @ID, @AddressLine1 = @AddressLine1, @AddressLine2 = @AddressLine2, @AddressLine1Bangla = @AddressLine1Bangla, @DivisionID = @DivisionID, @DistrictID = @DistrictID, @UpazilaID = @UpazilaID, @UnionID = @UnionID, @MauzaID = @MauzaID, @VillageID = @VillageID, @PostOfficeID = @PostOfficeID, @TelephoneNo = @TelephoneNo, @MobileNo = @MobileNo, @Email = @Email", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> AuthenticateUserAsync(int? employeeID, string userName, string password, string secretKey, OutputParameter<byte[]> token, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterToken = new SqlParameter
            {
                ParameterName = "Token",
                Size = 256,
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = token?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.VarBinary,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "EmployeeID",
                    Value = employeeID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "UserName",
                    Size = 100,
                    Value = userName ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Password",
                    Size = 50,
                    Value = password ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "SecretKey",
                    Size = 100,
                    Value = secretKey ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                parameterToken,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [sec].[AuthenticateUser] @EmployeeID = @EmployeeID, @UserName = @UserName, @Password = @Password, @SecretKey = @SecretKey, @Token = @Token OUTPUT", sqlParameters, cancellationToken);

            token?.SetValue(parameterToken.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> CreateEmployeeAsync(byte[] token, string secretKey, string pIN, string firstName, string lastName, string email, string phone, DateOnly? joiningDate, int? presentAddressID, int? permanentAddressID, byte? jobTypeID, byte? jobStatusID, byte? departmentID, byte? designationID, byte? jobGradeID, int? managerID, OutputParameter<int?> iD, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterID = new SqlParameter
            {
                ParameterName = "ID",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = iD?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Token",
                    Size = 256,
                    Value = token ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarBinary,
                },
                new SqlParameter
                {
                    ParameterName = "SecretKey",
                    Size = 100,
                    Value = secretKey ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "PIN",
                    Size = 10,
                    Value = pIN ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "FirstName",
                    Size = 50,
                    Value = firstName ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "LastName",
                    Size = 50,
                    Value = lastName ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Email",
                    Size = 50,
                    Value = email ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Phone",
                    Size = 15,
                    Value = phone ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "JoiningDate",
                    Value = joiningDate ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Date,
                },
                new SqlParameter
                {
                    ParameterName = "PresentAddressID",
                    Value = presentAddressID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "PermanentAddressID",
                    Value = permanentAddressID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "JobTypeID",
                    Value = jobTypeID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.TinyInt,
                },
                new SqlParameter
                {
                    ParameterName = "JobStatusID",
                    Value = jobStatusID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.TinyInt,
                },
                new SqlParameter
                {
                    ParameterName = "DepartmentID",
                    Value = departmentID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.TinyInt,
                },
                new SqlParameter
                {
                    ParameterName = "DesignationID",
                    Value = designationID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.TinyInt,
                },
                new SqlParameter
                {
                    ParameterName = "JobGradeID",
                    Value = jobGradeID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.TinyInt,
                },
                new SqlParameter
                {
                    ParameterName = "ManagerID",
                    Value = managerID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterID,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [hr].[CreateEmployee] @Token = @Token, @SecretKey = @SecretKey, @PIN = @PIN, @FirstName = @FirstName, @LastName = @LastName, @Email = @Email, @Phone = @Phone, @JoiningDate = @JoiningDate, @PresentAddressID = @PresentAddressID, @PermanentAddressID = @PermanentAddressID, @JobTypeID = @JobTypeID, @JobStatusID = @JobStatusID, @DepartmentID = @DepartmentID, @DesignationID = @DesignationID, @JobGradeID = @JobGradeID, @ManagerID = @ManagerID, @ID = @ID OUTPUT", sqlParameters, cancellationToken);

            iD?.SetValue(parameterID.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> CreateIndividualClientAsync(byte[] token, string secretKey, bool? isMember, bool? isInstitution, DateOnly? savingsOpeningDate, int? savingsNo, decimal? savingsBalance, int? introducerMemNo, byte? clientStatusID, DateOnly? clientStatusEffectiveDate, DateOnly? iDIssueDate, DateTime? setDate, string clientName, string clientLastName, string clientNameBangla, string fatherName, string fatherNameBang, int? fatherClientNo, string motherName, string motherNameBang, int? motherClientNo, string spouseName, string spouseNameBang, int? spouseClientNo, byte? professionID, string gender, string religion, string maritalStatus, string bloodGroup, DateTime? dateOfBirth, int? presentAddressID, int? permanentAddressID, string employerName, int? employerAddressID, string nID, string passportNo, string tIN, int? birthPlaceDistrictID, string educationalQualification, string birthCertificateNo, OutputParameter<int?> iD, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterID = new SqlParameter
            {
                ParameterName = "ID",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = iD?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Token",
                    Size = 256,
                    Value = token ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarBinary,
                },
                new SqlParameter
                {
                    ParameterName = "SecretKey",
                    Size = 100,
                    Value = secretKey ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "IsMember",
                    Value = isMember ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                new SqlParameter
                {
                    ParameterName = "IsInstitution",
                    Value = isInstitution ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                new SqlParameter
                {
                    ParameterName = "SavingsOpeningDate",
                    Value = savingsOpeningDate ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Date,
                },
                new SqlParameter
                {
                    ParameterName = "SavingsNo",
                    Value = savingsNo ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "SavingsBalance",
                    Precision = 19,
                    Scale = 4,
                    Value = savingsBalance ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Money,
                },
                new SqlParameter
                {
                    ParameterName = "IntroducerMemNo",
                    Value = introducerMemNo ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "ClientStatusID",
                    Value = clientStatusID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.TinyInt,
                },
                new SqlParameter
                {
                    ParameterName = "ClientStatusEffectiveDate",
                    Value = clientStatusEffectiveDate ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Date,
                },
                new SqlParameter
                {
                    ParameterName = "IDIssueDate",
                    Value = iDIssueDate ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Date,
                },
                new SqlParameter
                {
                    ParameterName = "SetDate",
                    Value = setDate ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.SmallDateTime,
                },
                new SqlParameter
                {
                    ParameterName = "ClientName",
                    Size = 100,
                    Value = clientName ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "ClientLastName",
                    Size = 50,
                    Value = clientLastName ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "ClientNameBangla",
                    Size = 100,
                    Value = clientNameBangla ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "FatherName",
                    Size = 50,
                    Value = fatherName ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "FatherNameBang",
                    Size = 50,
                    Value = fatherNameBang ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "FatherClientNo",
                    Value = fatherClientNo ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "MotherName",
                    Size = 50,
                    Value = motherName ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "MotherNameBang",
                    Size = 50,
                    Value = motherNameBang ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "MotherClientNo",
                    Value = motherClientNo ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "SpouseName",
                    Size = 150,
                    Value = spouseName ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "SpouseNameBang",
                    Size = 50,
                    Value = spouseNameBang ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "SpouseClientNo",
                    Value = spouseClientNo ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "ProfessionID",
                    Value = professionID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.TinyInt,
                },
                new SqlParameter
                {
                    ParameterName = "Gender",
                    Size = 1,
                    Value = gender ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Char,
                },
                new SqlParameter
                {
                    ParameterName = "Religion",
                    Size = 1,
                    Value = religion ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Char,
                },
                new SqlParameter
                {
                    ParameterName = "MaritalStatus",
                    Size = 1,
                    Value = maritalStatus ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Char,
                },
                new SqlParameter
                {
                    ParameterName = "BloodGroup",
                    Size = 3,
                    Value = bloodGroup ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "DateOfBirth",
                    Value = dateOfBirth ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.SmallDateTime,
                },
                new SqlParameter
                {
                    ParameterName = "PresentAddressID",
                    Value = presentAddressID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "PermanentAddressID",
                    Value = permanentAddressID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "EmployerName",
                    Size = 50,
                    Value = employerName ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "EmployerAddressID",
                    Value = employerAddressID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "NID",
                    Size = 50,
                    Value = nID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "PassportNo",
                    Size = 50,
                    Value = passportNo ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "TIN",
                    Size = 50,
                    Value = tIN ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "BirthPlaceDistrictID",
                    Value = birthPlaceDistrictID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "EducationalQualification",
                    Size = 100,
                    Value = educationalQualification ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "BirthCertificateNo",
                    Size = 50,
                    Value = birthCertificateNo ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                parameterID,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [cl].[CreateIndividualClient] @Token = @Token, @SecretKey = @SecretKey, @IsMember = @IsMember, @IsInstitution = @IsInstitution, @SavingsOpeningDate = @SavingsOpeningDate, @SavingsNo = @SavingsNo, @SavingsBalance = @SavingsBalance, @IntroducerMemNo = @IntroducerMemNo, @ClientStatusID = @ClientStatusID, @ClientStatusEffectiveDate = @ClientStatusEffectiveDate, @IDIssueDate = @IDIssueDate, @SetDate = @SetDate, @ClientName = @ClientName, @ClientLastName = @ClientLastName, @ClientNameBangla = @ClientNameBangla, @FatherName = @FatherName, @FatherNameBang = @FatherNameBang, @FatherClientNo = @FatherClientNo, @MotherName = @MotherName, @MotherNameBang = @MotherNameBang, @MotherClientNo = @MotherClientNo, @SpouseName = @SpouseName, @SpouseNameBang = @SpouseNameBang, @SpouseClientNo = @SpouseClientNo, @ProfessionID = @ProfessionID, @Gender = @Gender, @Religion = @Religion, @MaritalStatus = @MaritalStatus, @BloodGroup = @BloodGroup, @DateOfBirth = @DateOfBirth, @PresentAddressID = @PresentAddressID, @PermanentAddressID = @PermanentAddressID, @EmployerName = @EmployerName, @EmployerAddressID = @EmployerAddressID, @NID = @NID, @PassportNo = @PassportNo, @TIN = @TIN, @BirthPlaceDistrictID = @BirthPlaceDistrictID, @EducationalQualification = @EducationalQualification, @BirthCertificateNo = @BirthCertificateNo, @ID = @ID OUTPUT", sqlParameters, cancellationToken);

            iD?.SetValue(parameterID.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> CreateInstitutionalClientAsync(byte[] token, string secretKey, bool? isMember, bool? isInstitution, DateOnly? savingsOpeningDate, int? savingsNo, decimal? savingsBalance, int? introducerMemNo, byte? clientStatusID, DateOnly? clientStatusEffectiveDate, DateOnly? iDIssueDate, DateTime? setDate, string clientName, string clientNameBangla, string signatoryName1, string signatoryName2, int? addressID, string tradelicenseNo, string regNo, OutputParameter<int?> iD, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterID = new SqlParameter
            {
                ParameterName = "ID",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = iD?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Token",
                    Size = 256,
                    Value = token ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarBinary,
                },
                new SqlParameter
                {
                    ParameterName = "SecretKey",
                    Size = 100,
                    Value = secretKey ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "IsMember",
                    Value = isMember ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                new SqlParameter
                {
                    ParameterName = "IsInstitution",
                    Value = isInstitution ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                new SqlParameter
                {
                    ParameterName = "SavingsOpeningDate",
                    Value = savingsOpeningDate ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Date,
                },
                new SqlParameter
                {
                    ParameterName = "SavingsNo",
                    Value = savingsNo ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "SavingsBalance",
                    Precision = 19,
                    Scale = 4,
                    Value = savingsBalance ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Money,
                },
                new SqlParameter
                {
                    ParameterName = "IntroducerMemNo",
                    Value = introducerMemNo ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "ClientStatusID",
                    Value = clientStatusID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.TinyInt,
                },
                new SqlParameter
                {
                    ParameterName = "ClientStatusEffectiveDate",
                    Value = clientStatusEffectiveDate ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Date,
                },
                new SqlParameter
                {
                    ParameterName = "IDIssueDate",
                    Value = iDIssueDate ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Date,
                },
                new SqlParameter
                {
                    ParameterName = "SetDate",
                    Value = setDate ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.SmallDateTime,
                },
                new SqlParameter
                {
                    ParameterName = "ClientName",
                    Size = 100,
                    Value = clientName ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "ClientNameBangla",
                    Size = 100,
                    Value = clientNameBangla ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "SignatoryName1",
                    Size = 100,
                    Value = signatoryName1 ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "SignatoryName2",
                    Size = 100,
                    Value = signatoryName2 ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "AddressID",
                    Value = addressID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "TradelicenseNo",
                    Size = 50,
                    Value = tradelicenseNo ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "RegNo",
                    Size = 50,
                    Value = regNo ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                parameterID,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [cl].[CreateInstitutionalClient] @Token = @Token, @SecretKey = @SecretKey, @IsMember = @IsMember, @IsInstitution = @IsInstitution, @SavingsOpeningDate = @SavingsOpeningDate, @SavingsNo = @SavingsNo, @SavingsBalance = @SavingsBalance, @IntroducerMemNo = @IntroducerMemNo, @ClientStatusID = @ClientStatusID, @ClientStatusEffectiveDate = @ClientStatusEffectiveDate, @IDIssueDate = @IDIssueDate, @SetDate = @SetDate, @ClientName = @ClientName, @ClientNameBangla = @ClientNameBangla, @SignatoryName1 = @SignatoryName1, @SignatoryName2 = @SignatoryName2, @AddressID = @AddressID, @TradelicenseNo = @TradelicenseNo, @RegNo = @RegNo, @ID = @ID OUTPUT", sqlParameters, cancellationToken);

            iD?.SetValue(parameterID.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> CreateMemberAsync(byte[] token, string secretKey, int? clientID, int? memberNo, DateOnly? membershipDate, decimal? shareBalance, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Token",
                    Size = 256,
                    Value = token ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarBinary,
                },
                new SqlParameter
                {
                    ParameterName = "SecretKey",
                    Size = 100,
                    Value = secretKey ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "ClientID",
                    Value = clientID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "MemberNo",
                    Value = memberNo ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "MembershipDate",
                    Value = membershipDate ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Date,
                },
                new SqlParameter
                {
                    ParameterName = "ShareBalance",
                    Precision = 19,
                    Scale = 4,
                    Value = shareBalance ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Money,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [cl].[CreateMember] @Token = @Token, @SecretKey = @SecretKey, @ClientID = @ClientID, @MemberNo = @MemberNo, @MembershipDate = @MembershipDate, @ShareBalance = @ShareBalance", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> DecryptTokenAsync(byte[] token, string secretKey, OutputParameter<int?> iD, OutputParameter<byte?> roleID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterID = new SqlParameter
            {
                ParameterName = "ID",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = iD?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterRoleID = new SqlParameter
            {
                ParameterName = "RoleID",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = roleID?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.TinyInt,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Token",
                    Size = 256,
                    Value = token ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarBinary,
                },
                new SqlParameter
                {
                    ParameterName = "SecretKey",
                    Size = 100,
                    Value = secretKey ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                parameterID,
                parameterRoleID,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [sec].[DecryptToken] @Token = @Token, @SecretKey = @SecretKey, @ID = @ID OUTPUT, @RoleID = @RoleID OUTPUT", sqlParameters, cancellationToken);

            iD?.SetValue(parameterID.Value);
            roleID?.SetValue(parameterRoleID.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> DeleteClientAsync(byte[] token, string secretKey, int? iD, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Token",
                    Size = 256,
                    Value = token ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarBinary,
                },
                new SqlParameter
                {
                    ParameterName = "SecretKey",
                    Size = 100,
                    Value = secretKey ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "ID",
                    Value = iD ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [cl].[DeleteClient] @Token = @Token, @SecretKey = @SecretKey, @ID = @ID", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> DeleteEmployeeAsync(byte[] token, string secretKey, int? iD, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Token",
                    Size = 256,
                    Value = token ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarBinary,
                },
                new SqlParameter
                {
                    ParameterName = "SecretKey",
                    Size = 100,
                    Value = secretKey ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "ID",
                    Value = iD ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [hr].[DeleteEmployee] @Token = @Token, @SecretKey = @SecretKey, @ID = @ID", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<findResult>> findAsync(string name, string type, string schema, long? rowsMin, long? rowsMax, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "name",
                    Size = 200,
                    Value = name ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "type",
                    Size = 100,
                    Value = type ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "schema",
                    Size = 50,
                    Value = schema ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "rowsMin",
                    Value = rowsMin ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.BigInt,
                },
                new SqlParameter
                {
                    ParameterName = "rowsMax",
                    Value = rowsMax ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.BigInt,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<findResult>("EXEC @returnValue = [mintu].[find] @name = @name, @type = @type, @schema = @schema, @rowsMin = @rowsMin, @rowsMax = @rowsMax", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<lookupResult>> lookupAsync(string @object, string q1, string q2, string q3, string q4, string q5, string q6, string q7, string q8, string q9, string q10, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Object",
                    Size = 1000,
                    Value = @object ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Q1",
                    Size = -1,
                    Value = q1 ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Q2",
                    Size = -1,
                    Value = q2 ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Q3",
                    Size = -1,
                    Value = q3 ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Q4",
                    Size = -1,
                    Value = q4 ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Q5",
                    Size = -1,
                    Value = q5 ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Q6",
                    Size = -1,
                    Value = q6 ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Q7",
                    Size = -1,
                    Value = q7 ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Q8",
                    Size = -1,
                    Value = q8 ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Q9",
                    Size = -1,
                    Value = q9 ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Q10",
                    Size = -1,
                    Value = q10 ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<lookupResult>("EXEC @returnValue = [mintu].[lookup] @Object = @Object, @Q1 = @Q1, @Q2 = @Q2, @Q3 = @Q3, @Q4 = @Q4, @Q5 = @Q5, @Q6 = @Q6, @Q7 = @Q7, @Q8 = @Q8, @Q9 = @Q9, @Q10 = @Q10", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<showResult>> showAsync(string @object, string query, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Object",
                    Size = 1000,
                    Value = @object ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Query",
                    Size = -1,
                    Value = query ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<showResult>("EXEC @returnValue = [mintu].[show] @Object = @Object, @Query = @Query", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> UpdateClientAsync(byte[] token, string secretKey, int? iD, bool? isMember, bool? isInstitution, DateOnly? savingsOpeningDate, int? savingsNo, decimal? savingsBalance, int? introducerMemNo, byte? clientStatusID, DateOnly? clientStatusEffectiveDate, DateOnly? iDIssueDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Token",
                    Size = 256,
                    Value = token ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarBinary,
                },
                new SqlParameter
                {
                    ParameterName = "SecretKey",
                    Size = 100,
                    Value = secretKey ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "ID",
                    Value = iD ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "IsMember",
                    Value = isMember ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                new SqlParameter
                {
                    ParameterName = "IsInstitution",
                    Value = isInstitution ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                new SqlParameter
                {
                    ParameterName = "SavingsOpeningDate",
                    Value = savingsOpeningDate ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Date,
                },
                new SqlParameter
                {
                    ParameterName = "SavingsNo",
                    Value = savingsNo ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "SavingsBalance",
                    Precision = 19,
                    Scale = 4,
                    Value = savingsBalance ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Money,
                },
                new SqlParameter
                {
                    ParameterName = "IntroducerMemNo",
                    Value = introducerMemNo ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "ClientStatusID",
                    Value = clientStatusID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.TinyInt,
                },
                new SqlParameter
                {
                    ParameterName = "ClientStatusEffectiveDate",
                    Value = clientStatusEffectiveDate ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Date,
                },
                new SqlParameter
                {
                    ParameterName = "IDIssueDate",
                    Value = iDIssueDate ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Date,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [cl].[UpdateClient] @Token = @Token, @SecretKey = @SecretKey, @ID = @ID, @IsMember = @IsMember, @IsInstitution = @IsInstitution, @SavingsOpeningDate = @SavingsOpeningDate, @SavingsNo = @SavingsNo, @SavingsBalance = @SavingsBalance, @IntroducerMemNo = @IntroducerMemNo, @ClientStatusID = @ClientStatusID, @ClientStatusEffectiveDate = @ClientStatusEffectiveDate, @IDIssueDate = @IDIssueDate", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> UpdateEmployeeAsync(byte[] token, string secretKey, int? iD, string firstName, string lastName, string email, string phone, DateOnly? joiningDate, DateOnly? separationDate, int? presentAddressID, int? permanentAddressID, byte? jobTypeID, byte? jobStatusID, byte? departmentID, byte? designationID, byte? jobGradeID, int? managerID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Token",
                    Size = 256,
                    Value = token ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarBinary,
                },
                new SqlParameter
                {
                    ParameterName = "SecretKey",
                    Size = 100,
                    Value = secretKey ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "ID",
                    Value = iD ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "FirstName",
                    Size = 50,
                    Value = firstName ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "LastName",
                    Size = 50,
                    Value = lastName ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Email",
                    Size = 50,
                    Value = email ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Phone",
                    Size = 15,
                    Value = phone ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "JoiningDate",
                    Value = joiningDate ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Date,
                },
                new SqlParameter
                {
                    ParameterName = "SeparationDate",
                    Value = separationDate ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Date,
                },
                new SqlParameter
                {
                    ParameterName = "PresentAddressID",
                    Value = presentAddressID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "PermanentAddressID",
                    Value = permanentAddressID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "JobTypeID",
                    Value = jobTypeID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.TinyInt,
                },
                new SqlParameter
                {
                    ParameterName = "JobStatusID",
                    Value = jobStatusID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.TinyInt,
                },
                new SqlParameter
                {
                    ParameterName = "DepartmentID",
                    Value = departmentID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.TinyInt,
                },
                new SqlParameter
                {
                    ParameterName = "DesignationID",
                    Value = designationID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.TinyInt,
                },
                new SqlParameter
                {
                    ParameterName = "JobGradeID",
                    Value = jobGradeID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.TinyInt,
                },
                new SqlParameter
                {
                    ParameterName = "ManagerID",
                    Value = managerID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [hr].[UpdateEmployee] @Token = @Token, @SecretKey = @SecretKey, @ID = @ID, @FirstName = @FirstName, @LastName = @LastName, @Email = @Email, @Phone = @Phone, @JoiningDate = @JoiningDate, @SeparationDate = @SeparationDate, @PresentAddressID = @PresentAddressID, @PermanentAddressID = @PermanentAddressID, @JobTypeID = @JobTypeID, @JobStatusID = @JobStatusID, @DepartmentID = @DepartmentID, @DesignationID = @DesignationID, @JobGradeID = @JobGradeID, @ManagerID = @ManagerID", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> VerifyClientAsync(byte[] token, string secretKey, int? iD, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Token",
                    Size = 256,
                    Value = token ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarBinary,
                },
                new SqlParameter
                {
                    ParameterName = "SecretKey",
                    Size = 100,
                    Value = secretKey ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "ID",
                    Value = iD ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [cl].[VerifyClient] @Token = @Token, @SecretKey = @SecretKey, @ID = @ID", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> VerifyEmployeeAsync(byte[] token, string secretKey, int? iD, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Token",
                    Size = 256,
                    Value = token ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarBinary,
                },
                new SqlParameter
                {
                    ParameterName = "SecretKey",
                    Size = 100,
                    Value = secretKey ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "ID",
                    Value = iD ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [hr].[VerifyEmployee] @Token = @Token, @SecretKey = @SecretKey, @ID = @ID", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
