// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Banyan.Entities.Models;

public partial class MemberProfile
{
    public int ClientId { get; set; }

    public int? MemberNo { get; set; }

    public DateOnly? MembershipDate { get; set; }

    public decimal? ShareBalance { get; set; }

    public virtual IndividualDetails Client { get; set; }
}