// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Banyan.Entities.Models;

public partial class MemberInfo
{
    public int MemNo { get; set; }

    public byte? MemberCategoryId { get; set; }

    public string MemberTypeId { get; set; }

    public string MemberName { get; set; }

    public string FullNameBang { get; set; }

    public string MemberLastName { get; set; }

    public string FatherName { get; set; }

    public string FatherNameBang { get; set; }

    public int? FatherMemNo { get; set; }

    public string MotherName { get; set; }

    public string MotherNameBang { get; set; }

    public int? MotherMemNo { get; set; }

    public string SpouseName { get; set; }

    public string SpouseNameBang { get; set; }

    public int? SpouseMemNo { get; set; }

    public byte? ProfessionId { get; set; }

    public string Gender { get; set; }

    public string Religion { get; set; }

    public bool IsStaff { get; set; }

    public string MaritalStatus { get; set; }

    public string BloodGroup { get; set; }

    public DateTime? DateOfBirth { get; set; }

    public DateTime? AccountOpeningDate { get; set; }

    public int? PresentAddressId { get; set; }

    public int? PermanentAddressId { get; set; }

    public string EmployerName { get; set; }

    public int? EmployerAddressId { get; set; }

    public int? IntroducerMemNo { get; set; }

    public int? IntroducerMemNo2 { get; set; }

    public string Nid { get; set; }

    public string PassportNo { get; set; }

    public string Tin { get; set; }

    public byte? MemberStatusId { get; set; }

    public DateOnly? MemberStatusEffectiveDate { get; set; }

    public DateOnly? IdissueDate { get; set; }

    public int? PlaceOfBirth { get; set; }

    public string EducationalQualification { get; set; }

    public string BirthCertificateNo { get; set; }

    public virtual MemberInfo FatherMemNoNavigation { get; set; }

    public virtual ICollection<MemberInfo> InverseFatherMemNoNavigation { get; set; } = new List<MemberInfo>();

    public virtual ICollection<MemberInfo> InverseMotherMemNoNavigation { get; set; } = new List<MemberInfo>();

    public virtual ICollection<MemberInfo> InverseSpouseMemNoNavigation { get; set; } = new List<MemberInfo>();

    public virtual ClientStatus MemberStatus { get; set; }

    public virtual MemberInfo MotherMemNoNavigation { get; set; }

    public virtual Profession Profession { get; set; }

    public virtual ICollection<SavingsAccounts> SavingsAccounts { get; set; } = new List<SavingsAccounts>();

    public virtual MemberInfo SpouseMemNoNavigation { get; set; }
}