// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Banyan.Entities.Models;

public partial class PostOffice
{
    public int? CountryId { get; set; }

    public int? DivisionId { get; set; }

    public int? DistrictId { get; set; }

    public int? UpazilaId { get; set; }

    public int Id { get; set; }

    public string PostOffice1 { get; set; }

    public int? PostCode { get; set; }
}