// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Banyan.Entities.Models;

public partial class RolePrivilege
{
    public byte RoleId { get; set; }

    public short PrivilegeId { get; set; }

    public bool? CanSelect { get; set; }

    public bool? CanInsert { get; set; }

    public bool? CanUpdate { get; set; }

    public bool? CanDelete { get; set; }

    public bool? CanVerify { get; set; }

    public bool? CanRestore { get; set; }

    public bool? IsActive { get; set; }

    public virtual Privilege Privilege { get; set; }

    public virtual Role Role { get; set; }
}