// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Banyan.Entities.Models;

public partial class SavingsAccounts
{
    public int Id { get; set; }

    public int MemNo { get; set; }

    public DateOnly OpenedDate { get; set; }

    public decimal Balance { get; set; }

    public byte AccountStatusId { get; set; }

    public virtual MemberInfo MemNoNavigation { get; set; }

    public virtual SavingsTransactions SavingsTransactions { get; set; }
}