// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Banyan.Entities.Models;

public partial class SavingsTransactions
{
    public int Id { get; set; }

    public int SavingsAccountId { get; set; }

    public byte SavingsTransactionTypeId { get; set; }

    public decimal Amount { get; set; }

    public DateOnly TransactionDate { get; set; }

    public decimal BalanceAfter { get; set; }

    public int? JournalEntryId { get; set; }

    public virtual SavingsAccounts IdNavigation { get; set; }
}