// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Banyan.Entities.Models;

public partial class Settings
{
    public short Id { get; set; }

    public decimal? MinimumBalance { get; set; }

    public decimal? GeneralInterestRate { get; set; }

    public DateOnly? EffectiveDate { get; set; }

    public bool? IsActive { get; set; }
}