// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Banyan.Entities.Models;

public partial class Union
{
    public int? PauraShavaAreaId { get; set; }

    public int Id { get; set; }

    public int? DivisionId { get; set; }

    public int? DistrictId { get; set; }

    public int? UpazilaId { get; set; }

    public string DivisionCode { get; set; }

    public string DistrictCode { get; set; }

    public string UpazilaCode { get; set; }

    public string PsaCode { get; set; }

    public string UnionCode { get; set; }

    public string UnionName { get; set; }

    public string PaurashavaAreaName { get; set; }

    public string DivisionName { get; set; }

    public string DistrictName { get; set; }

    public string UpazilaName { get; set; }

    public string AllInOne { get; set; }

    public string Status { get; set; }

    public bool? IsActive { get; set; }

    public string InactivationNote { get; set; }

    public virtual ICollection<AddressBook> AddressBook { get; set; } = new List<AddressBook>();

    public virtual ICollection<Mauza> Mauza { get; set; } = new List<Mauza>();

    public virtual Upazila Upazila { get; set; }
}