// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Banyan.Entities.Models;

public partial class Upazila
{
    public int? CountryId { get; set; }

    public int? DivisionId { get; set; }

    public int? DistrictId { get; set; }

    public int Id { get; set; }

    public string DivisionCode { get; set; }

    public string DistrictCode { get; set; }

    public string UpazilaCode { get; set; }

    public string HrDivisionId { get; set; }

    public string HrDistrictId { get; set; }

    public string HrUpazilaId { get; set; }

    public string HrUpazilaId2 { get; set; }

    public string HrUpazilaId3 { get; set; }

    public string HrUpazilaId4 { get; set; }

    public string AccountDistrictId { get; set; }

    public string AccountUpazilaId { get; set; }

    public string CurrentAccountCode { get; set; }

    public string DivisionName { get; set; }

    public string DistrictName { get; set; }

    public string UpazilaName { get; set; }

    public double? Lat { get; set; }

    public double? Long { get; set; }

    public double? LatOld { get; set; }

    public double? LongOld { get; set; }

    public string AllInOne { get; set; }

    public string Status { get; set; }

    public bool? IsActive { get; set; }

    public string InactivationNote { get; set; }

    public bool? IsThana { get; set; }

    public virtual District District { get; set; }

    public virtual ICollection<PauraShavaArea> PauraShavaArea { get; set; } = new List<PauraShavaArea>();

    public virtual ICollection<Union> Union { get; set; } = new List<Union>();
}