// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Banyan.Entities.Models;

public partial class Users
{
    public int Id { get; set; }

    public int? EmployeeId { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public byte? RoleId { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? EffectiveDate { get; set; }

    public int? UserId { get; set; }

    public DateTime? SetDate { get; set; }
}