// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Banyan.Entities.Models;

public partial class Village2
{
    public int Id { get; set; }

    public int? Id2 { get; set; }

    public int? VillageCode { get; set; }

    public string VillageName { get; set; }

    public int? PostOfficeCode { get; set; }

    public int? DiviCode { get; set; }

    public int? DistCode { get; set; }

    public int? UpzilaCode { get; set; }

    public int? ThanaCode { get; set; }

    public string VillageNameBang { get; set; }
}