// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Banyan.Entities.Models;
using Microsoft.EntityFrameworkCore;

namespace Banyan.Data.Models;

public partial class MCCCULContext : DbContext
{
    public MCCCULContext(DbContextOptions<MCCCULContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AccountStatus> AccountStatus { get; set; }

    public virtual DbSet<AddressBook> AddressBook { get; set; }

    public virtual DbSet<Client> Client { get; set; }

    public virtual DbSet<ClientHistory> ClientHistory { get; set; }

    public virtual DbSet<ClientStatus> ClientStatus { get; set; }

    public virtual DbSet<Country> Country { get; set; }

    public virtual DbSet<Department> Department { get; set; }

    public virtual DbSet<Designation> Designation { get; set; }

    public virtual DbSet<District> District { get; set; }

    public virtual DbSet<Division> Division { get; set; }

    public virtual DbSet<Employee> Employee { get; set; }

    public virtual DbSet<EmployeeHistory> EmployeeHistory { get; set; }

    public virtual DbSet<GradeBand> GradeBand { get; set; }

    public virtual DbSet<IndividualDetails> IndividualDetails { get; set; }

    public virtual DbSet<InstitutionDetails> InstitutionDetails { get; set; }

    public virtual DbSet<JobGrade> JobGrade { get; set; }

    public virtual DbSet<JobStatus> JobStatus { get; set; }

    public virtual DbSet<Jobtype> Jobtype { get; set; }

    public virtual DbSet<Mauza> Mauza { get; set; }

    public virtual DbSet<MemberInfo> MemberInfo { get; set; }

    public virtual DbSet<MemberProfile> MemberProfile { get; set; }

    public virtual DbSet<PauraShavaArea> PauraShavaArea { get; set; }

    public virtual DbSet<PostOffice> PostOffice { get; set; }

    public virtual DbSet<Privilege> Privilege { get; set; }

    public virtual DbSet<Profession> Profession { get; set; }

    public virtual DbSet<Role> Role { get; set; }

    public virtual DbSet<RolePrivilege> RolePrivilege { get; set; }

    public virtual DbSet<SavingsAccounts> SavingsAccounts { get; set; }

    public virtual DbSet<SavingsTransactionType> SavingsTransactionType { get; set; }

    public virtual DbSet<SavingsTransactions> SavingsTransactions { get; set; }

    public virtual DbSet<Settings> Settings { get; set; }

    public virtual DbSet<Union> Union { get; set; }

    public virtual DbSet<Upazila> Upazila { get; set; }

    public virtual DbSet<Users> Users { get; set; }

    public virtual DbSet<Village> Village { get; set; }

    public virtual DbSet<Village2> Village2 { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AccountStatus>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("AccountStatus", "acc");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Name)
                .HasMaxLength(10)
                .IsUnicode(false);
        });

        modelBuilder.Entity<AddressBook>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_Address");

            entity.ToTable("AddressBook", "ad");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.AddressLine1)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.AddressLine1Bangla).HasMaxLength(100);
            entity.Property(e => e.AddressLine2).HasMaxLength(100);
            entity.Property(e => e.DistrictId).HasColumnName("DistrictID");
            entity.Property(e => e.DivisionId).HasColumnName("DivisionID");
            entity.Property(e => e.Email)
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.MauzaId).HasColumnName("MauzaID");
            entity.Property(e => e.MobileNo)
                .HasMaxLength(15)
                .IsUnicode(false);
            entity.Property(e => e.PostOfficeId).HasColumnName("PostOfficeID");
            entity.Property(e => e.TelephoneNo)
                .HasMaxLength(15)
                .IsUnicode(false);
            entity.Property(e => e.UnionId).HasColumnName("UnionID");
            entity.Property(e => e.UpazilaId).HasColumnName("UpazilaID");
            entity.Property(e => e.VillageId).HasColumnName("VillageID");

            entity.HasOne(d => d.Union).WithMany(p => p.AddressBook)
                .HasForeignKey(d => d.UnionId)
                .HasConstraintName("FK_AddressBook_Union");
        });

        modelBuilder.Entity<Client>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Client__3214EC2717FFBAA5");

            entity.ToTable("Client", "cl", tb => tb.HasTrigger("tr_Client_Delete"));

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.ClientHistoryDate).HasPrecision(0);
            entity.Property(e => e.ClientStatusId).HasColumnName("ClientStatusID");
            entity.Property(e => e.IdissueDate).HasColumnName("IDIssueDate");
            entity.Property(e => e.SavingsBalance).HasColumnType("money");
            entity.Property(e => e.SetDate)
                .HasDefaultValueSql("(getdate())", "DF_Client_SetDate")
                .HasColumnType("smalldatetime");
            entity.Property(e => e.UserId).HasColumnName("UserID");
            entity.Property(e => e.VerifiedDate).HasColumnType("smalldatetime");

            entity.HasOne(d => d.ClientStatus).WithMany(p => p.Client)
                .HasForeignKey(d => d.ClientStatusId)
                .HasConstraintName("FK_Client_ClientStatus");
        });

        modelBuilder.Entity<ClientHistory>(entity =>
        {
            entity.HasKey(e => e.HistoryDate);

            entity.ToTable("ClientHistory", "cl");

            entity.Property(e => e.HistoryDate).HasPrecision(0);
            entity.Property(e => e.ClientHistoryDate).HasPrecision(0);
            entity.Property(e => e.ClientStatusId).HasColumnName("ClientStatusID");
            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.IdissueDate).HasColumnName("IDIssueDate");
            entity.Property(e => e.SavingsBalance).HasColumnType("money");
            entity.Property(e => e.SetDate).HasColumnType("smalldatetime");
            entity.Property(e => e.UserId).HasColumnName("UserID");
            entity.Property(e => e.VerifiedDate).HasColumnType("smalldatetime");
        });

        modelBuilder.Entity<ClientStatus>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__MemberSt__3214EC27529D0A5A");

            entity.ToTable("ClientStatus", "cl");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Name)
                .HasMaxLength(10)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Country>(entity =>
        {
            entity.ToTable("Country", "ad");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("ID");
            entity.Property(e => e.CountryName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.HrCode)
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength()
                .HasColumnName("HR_Code");
            entity.Property(e => e.Iso2)
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength()
                .HasColumnName("ISO2");
            entity.Property(e => e.Iso3)
                .HasMaxLength(5)
                .IsUnicode(false)
                .HasColumnName("ISO3");
            entity.Property(e => e.Nationality)
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Department>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Departme__3214EC27BD3F85E8");

            entity.ToTable("Department", "hr");

            entity.HasIndex(e => e.Name, "UQ__Departme__737584F69767C24A").IsUnique();

            entity.Property(e => e.Id)
                .ValueGeneratedOnAdd()
                .HasColumnName("ID");
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<Designation>(entity =>
        {
            entity.ToTable("Designation", "hr");

            entity.Property(e => e.Id)
                .ValueGeneratedOnAdd()
                .HasColumnName("ID");
            entity.Property(e => e.Name).HasMaxLength(50);
        });

        modelBuilder.Entity<District>(entity =>
        {
            entity.ToTable("District", "ad");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("ID");
            entity.Property(e => e.AccountDistrictId)
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength()
                .HasColumnName("Account_DistrictID");
            entity.Property(e => e.AllInOne)
                .HasMaxLength(2000)
                .IsUnicode(false);
            entity.Property(e => e.CountryId).HasColumnName("CountryID");
            entity.Property(e => e.DistrictCode)
                .IsRequired()
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.DistrictName)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.DivisionCode)
                .IsRequired()
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.DivisionId).HasColumnName("DivisionID");
            entity.Property(e => e.DivisionName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.HrDistrictId)
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength()
                .HasColumnName("HR_DistrictID");
            entity.Property(e => e.HrDivisionId)
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength()
                .HasColumnName("HR_DivisionID");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UserId)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("UserID");

            entity.HasOne(d => d.Division).WithMany(p => p.District)
                .HasForeignKey(d => d.DivisionId)
                .HasConstraintName("FK_District_Division");
        });

        modelBuilder.Entity<Division>(entity =>
        {
            entity.ToTable("Division", "ad");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("ID");
            entity.Property(e => e.CountryId).HasColumnName("CountryID");
            entity.Property(e => e.DivisionCode)
                .IsRequired()
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.DivisionName)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.HrDivisionId)
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength()
                .HasColumnName("HR_DivisionID");
            entity.Property(e => e.Status)
                .HasMaxLength(5)
                .IsUnicode(false);

            entity.HasOne(d => d.Country).WithMany(p => p.Division)
                .HasForeignKey(d => d.CountryId)
                .HasConstraintName("FK_Division_Country");
        });

        modelBuilder.Entity<Employee>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Employee__3214EC27624E9F9E");

            entity.ToTable("Employee", "hr", tb => tb.HasTrigger("tr_Employee_Delete"));

            entity.HasIndex(e => e.Email, "UQ__Employee__A9D10534CD0D4258").IsUnique();

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.DepartmentId).HasColumnName("DepartmentID");
            entity.Property(e => e.DesignationId).HasColumnName("DesignationID");
            entity.Property(e => e.Email)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.EmployeeHistoryDate).HasPrecision(0);
            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.JobGradeId).HasColumnName("JobGradeID");
            entity.Property(e => e.JobStatusId)
                .HasDefaultValue((byte)1, "DF__Employee__IsActi__1FEDB87C")
                .HasColumnName("JobStatusID");
            entity.Property(e => e.JobTypeId).HasColumnName("JobTypeID");
            entity.Property(e => e.LastName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ManagerId).HasColumnName("ManagerID");
            entity.Property(e => e.PermanentAddressId).HasColumnName("PermanentAddressID");
            entity.Property(e => e.Phone)
                .HasMaxLength(15)
                .IsUnicode(false);
            entity.Property(e => e.Pin)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("PIN");
            entity.Property(e => e.PresentAddressId).HasColumnName("PresentAddressID");
            entity.Property(e => e.SetDate)
                .HasDefaultValueSql("(getutcdate())", "DF__Employee__Create__20E1DCB5")
                .HasColumnType("smalldatetime");
            entity.Property(e => e.UserId).HasColumnName("UserID");
            entity.Property(e => e.VerifiedDate).HasColumnType("smalldatetime");

            entity.HasOne(d => d.Department).WithMany(p => p.Employee)
                .HasForeignKey(d => d.DepartmentId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_Employee_Department");

            entity.HasOne(d => d.Designation).WithMany(p => p.Employee)
                .HasForeignKey(d => d.DesignationId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_Employee_Designation");

            entity.HasOne(d => d.JobGrade).WithMany(p => p.Employee)
                .HasForeignKey(d => d.JobGradeId)
                .HasConstraintName("FK_Employee_JobGrade");

            entity.HasOne(d => d.JobStatus).WithMany(p => p.Employee)
                .HasForeignKey(d => d.JobStatusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Employee_JobStatus");

            entity.HasOne(d => d.JobType).WithMany(p => p.Employee)
                .HasForeignKey(d => d.JobTypeId)
                .HasConstraintName("FK_Employee_Jobtype");

            entity.HasOne(d => d.Manager).WithMany(p => p.InverseManager)
                .HasForeignKey(d => d.ManagerId)
                .HasConstraintName("FK_Employee_Manager");

            entity.HasOne(d => d.PermanentAddress).WithMany(p => p.EmployeePermanentAddress)
                .HasForeignKey(d => d.PermanentAddressId)
                .HasConstraintName("FK_Employee_AddressBook1");

            entity.HasOne(d => d.PresentAddress).WithMany(p => p.EmployeePresentAddress)
                .HasForeignKey(d => d.PresentAddressId)
                .HasConstraintName("FK_Employee_AddressBook");
        });

        modelBuilder.Entity<EmployeeHistory>(entity =>
        {
            entity.HasKey(e => e.HistoryDate);

            entity.ToTable("EmployeeHistory", "hr");

            entity.Property(e => e.HistoryDate).HasPrecision(0);
            entity.Property(e => e.DepartmentId).HasColumnName("DepartmentID");
            entity.Property(e => e.DesignationId).HasColumnName("DesignationID");
            entity.Property(e => e.Email)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.EmployeeHistoryDate).HasColumnType("datetime");
            entity.Property(e => e.FirstName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.JobGradeId).HasColumnName("JobGradeID");
            entity.Property(e => e.JobStatusId).HasColumnName("JobStatusID");
            entity.Property(e => e.JobTypeId).HasColumnName("JobTypeID");
            entity.Property(e => e.LastName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ManagerId).HasColumnName("ManagerID");
            entity.Property(e => e.PermanentAddressId).HasColumnName("PermanentAddressID");
            entity.Property(e => e.Phone)
                .HasMaxLength(15)
                .IsUnicode(false);
            entity.Property(e => e.Pin)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("PIN");
            entity.Property(e => e.PresentAddressId).HasColumnName("PresentAddressID");
            entity.Property(e => e.SetDate).HasColumnType("smalldatetime");
            entity.Property(e => e.UserId).HasColumnName("UserID");
            entity.Property(e => e.VerifiedDate).HasColumnType("smalldatetime");
        });

        modelBuilder.Entity<GradeBand>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_GradeType");

            entity.ToTable("GradeBand", "hr");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Description)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Name)
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        modelBuilder.Entity<IndividualDetails>(entity =>
        {
            entity.HasKey(e => e.ClientId);

            entity.ToTable("IndividualDetails", "cl", tb => tb.HasTrigger("tr_IndividualDetails_Delete"));

            entity.Property(e => e.ClientId)
                .ValueGeneratedNever()
                .HasColumnName("ClientID");
            entity.Property(e => e.BirthCertificateNo)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.BirthPlaceDistrictId).HasColumnName("BirthPlaceDistrictID");
            entity.Property(e => e.BloodGroup)
                .HasMaxLength(3)
                .IsUnicode(false);
            entity.Property(e => e.ClientLastName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ClientName)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ClientNameBangla).HasMaxLength(100);
            entity.Property(e => e.DateOfBirth).HasColumnType("smalldatetime");
            entity.Property(e => e.EducationalQualification)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.EmployerAddressId).HasColumnName("EmployerAddressID");
            entity.Property(e => e.EmployerName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.FatherName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.FatherNameBang).HasMaxLength(50);
            entity.Property(e => e.Gender)
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.MaritalStatus)
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.MotherName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.MotherNameBang).HasMaxLength(50);
            entity.Property(e => e.Nid)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("NID");
            entity.Property(e => e.PassportNo)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.PermanentAddressId).HasColumnName("PermanentAddressID");
            entity.Property(e => e.PresentAddressId).HasColumnName("PresentAddressID");
            entity.Property(e => e.ProfessionId).HasColumnName("ProfessionID");
            entity.Property(e => e.Religion)
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.SpouseName)
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.SpouseNameBang).HasMaxLength(50);
            entity.Property(e => e.Tin)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("TIN");

            entity.HasOne(d => d.BirthPlaceDistrict).WithMany(p => p.IndividualDetails)
                .HasForeignKey(d => d.BirthPlaceDistrictId)
                .HasConstraintName("FK_IndividualDetails_District");

            entity.HasOne(d => d.Client).WithOne(p => p.IndividualDetails)
                .HasForeignKey<IndividualDetails>(d => d.ClientId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_IndividualDetails_Client");

            entity.HasOne(d => d.FatherClientNoNavigation).WithMany(p => p.InverseFatherClientNoNavigation)
                .HasForeignKey(d => d.FatherClientNo)
                .HasConstraintName("FK_IndividualDetails_IndividualDetails");

            entity.HasOne(d => d.MotherClientNoNavigation).WithMany(p => p.InverseMotherClientNoNavigation)
                .HasForeignKey(d => d.MotherClientNo)
                .HasConstraintName("FK_IndividualDetails_IndividualDetails1");

            entity.HasOne(d => d.PermanentAddress).WithMany(p => p.IndividualDetailsPermanentAddress)
                .HasForeignKey(d => d.PermanentAddressId)
                .HasConstraintName("FK_IndividualDetails_AddressBook1");

            entity.HasOne(d => d.PresentAddress).WithMany(p => p.IndividualDetailsPresentAddress)
                .HasForeignKey(d => d.PresentAddressId)
                .HasConstraintName("FK_IndividualDetails_AddressBook");

            entity.HasOne(d => d.Profession).WithMany(p => p.IndividualDetails)
                .HasForeignKey(d => d.ProfessionId)
                .HasConstraintName("FK_IndividualDetails_Profession");

            entity.HasOne(d => d.SpouseClientNoNavigation).WithMany(p => p.InverseSpouseClientNoNavigation)
                .HasForeignKey(d => d.SpouseClientNo)
                .HasConstraintName("FK_IndividualDetails_IndividualDetails2");
        });

        modelBuilder.Entity<InstitutionDetails>(entity =>
        {
            entity.HasKey(e => e.ClientId);

            entity.ToTable("InstitutionDetails", "cl", tb => tb.HasTrigger("tr_InstitutionDetails_Delete"));

            entity.Property(e => e.ClientId)
                .ValueGeneratedNever()
                .HasColumnName("ClientID");
            entity.Property(e => e.AddressId).HasColumnName("AddressID");
            entity.Property(e => e.ClientName)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ClientNameBangla).HasMaxLength(100);
            entity.Property(e => e.RegNo)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.SignatoryName1)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.SignatoryName2)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.TradelicenseNo)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.Address).WithMany(p => p.InstitutionDetails)
                .HasForeignKey(d => d.AddressId)
                .HasConstraintName("FK_InstitutionDetails_AddressBook");

            entity.HasOne(d => d.Client).WithOne(p => p.InstitutionDetails)
                .HasForeignKey<InstitutionDetails>(d => d.ClientId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_InstitutionDetails_Client");
        });

        modelBuilder.Entity<JobGrade>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__JobGrade__3214EC27CC283919");

            entity.ToTable("JobGrade", "hr");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Description)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.GradeBandId).HasColumnName("GradeBandID");
            entity.Property(e => e.Name)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.GradeBand).WithMany(p => p.JobGrade)
                .HasForeignKey(d => d.GradeBandId)
                .HasConstraintName("FK_JobGrade_GradeBand");
        });

        modelBuilder.Entity<JobStatus>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__JobStatu__3214EC2732E21237");

            entity.ToTable("JobStatus", "hr");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Description)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Name)
                .HasMaxLength(30)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Jobtype>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Jobtype__3214EC273FCD938B");

            entity.ToTable("Jobtype", "hr");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Description)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Name)
                .HasMaxLength(30)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Mauza>(entity =>
        {
            entity.ToTable("Mauza", "ad");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("ID");
            entity.Property(e => e.AllInOne)
                .HasMaxLength(2000)
                .IsUnicode(false);
            entity.Property(e => e.DistrictCode)
                .IsRequired()
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.DistrictId).HasColumnName("DistrictID");
            entity.Property(e => e.DistrictName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.DivisionCode)
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.DivisionId).HasColumnName("DivisionID");
            entity.Property(e => e.DivisionName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.MauzaCode)
                .IsRequired()
                .HasMaxLength(3)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.MauzaName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.PaurashavaAreaId).HasColumnName("PaurashavaAreaID");
            entity.Property(e => e.PaurashavaName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.PsaCode)
                .IsRequired()
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.Status)
                .HasMaxLength(5)
                .IsUnicode(false);
            entity.Property(e => e.UnionCode)
                .IsRequired()
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.UnionId).HasColumnName("UnionID");
            entity.Property(e => e.UnionName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UpazilaCode)
                .IsRequired()
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.UpazilaId).HasColumnName("UpazilaID");
            entity.Property(e => e.UpazilaName)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.Union).WithMany(p => p.Mauza)
                .HasForeignKey(d => d.UnionId)
                .HasConstraintName("FK_Mauza_Union");
        });

        modelBuilder.Entity<MemberInfo>(entity =>
        {
            entity.HasKey(e => e.MemNo);

            entity.ToTable("MemberInfo", "mem", tb => tb.HasTrigger("tr_MemberInfo_StatusHistory"));

            entity.Property(e => e.MemNo).ValueGeneratedNever();
            entity.Property(e => e.AccountOpeningDate).HasColumnType("smalldatetime");
            entity.Property(e => e.BirthCertificateNo)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.BloodGroup)
                .HasMaxLength(3)
                .IsUnicode(false);
            entity.Property(e => e.DateOfBirth).HasColumnType("smalldatetime");
            entity.Property(e => e.EducationalQualification)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.EmployerAddressId).HasColumnName("EmployerAddressID");
            entity.Property(e => e.EmployerName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.FatherName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.FatherNameBang).HasMaxLength(50);
            entity.Property(e => e.FullNameBang).HasMaxLength(50);
            entity.Property(e => e.Gender)
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.IdissueDate).HasColumnName("IDIssueDate");
            entity.Property(e => e.MaritalStatus)
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.MemberCategoryId).HasColumnName("MemberCategoryID");
            entity.Property(e => e.MemberLastName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.MemberName)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.MemberStatusId).HasColumnName("MemberStatusID");
            entity.Property(e => e.MemberTypeId)
                .HasMaxLength(10)
                .IsUnicode(false)
                .IsFixedLength()
                .HasColumnName("MemberTypeID");
            entity.Property(e => e.MotherName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.MotherNameBang).HasMaxLength(50);
            entity.Property(e => e.Nid)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("NID");
            entity.Property(e => e.PassportNo)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.PermanentAddressId).HasColumnName("PermanentAddressID");
            entity.Property(e => e.PresentAddressId).HasColumnName("PresentAddressID");
            entity.Property(e => e.ProfessionId).HasColumnName("ProfessionID");
            entity.Property(e => e.Religion)
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.SpouseName)
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.SpouseNameBang).HasMaxLength(50);
            entity.Property(e => e.Tin)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("TIN");

            entity.HasOne(d => d.FatherMemNoNavigation).WithMany(p => p.InverseFatherMemNoNavigation)
                .HasForeignKey(d => d.FatherMemNo)
                .HasConstraintName("FK_MemberInfo_MemberInfo");

            entity.HasOne(d => d.MemberStatus).WithMany(p => p.MemberInfo)
                .HasForeignKey(d => d.MemberStatusId)
                .HasConstraintName("FK_MemberInfo_MemberStatus");

            entity.HasOne(d => d.MotherMemNoNavigation).WithMany(p => p.InverseMotherMemNoNavigation)
                .HasForeignKey(d => d.MotherMemNo)
                .HasConstraintName("FK_MemberInfo_MemberInfo1");

            entity.HasOne(d => d.Profession).WithMany(p => p.MemberInfo)
                .HasForeignKey(d => d.ProfessionId)
                .HasConstraintName("FK_MemberInfo_Profession");

            entity.HasOne(d => d.SpouseMemNoNavigation).WithMany(p => p.InverseSpouseMemNoNavigation)
                .HasForeignKey(d => d.SpouseMemNo)
                .HasConstraintName("FK_MemberInfo_MemberInfo2");
        });

        modelBuilder.Entity<MemberProfile>(entity =>
        {
            entity.HasKey(e => e.ClientId);

            entity.ToTable("MemberProfile", "cl");

            entity.Property(e => e.ClientId)
                .ValueGeneratedNever()
                .HasColumnName("ClientID");
            entity.Property(e => e.ShareBalance).HasColumnType("money");

            entity.HasOne(d => d.Client).WithOne(p => p.MemberProfile)
                .HasForeignKey<MemberProfile>(d => d.ClientId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MemberProfile_IndividualDetails");
        });

        modelBuilder.Entity<PauraShavaArea>(entity =>
        {
            entity.ToTable("PauraShavaArea", "ad");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("ID");
            entity.Property(e => e.AllInOne)
                .HasMaxLength(2000)
                .IsUnicode(false);
            entity.Property(e => e.DistrictCode)
                .IsRequired()
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.DistrictId).HasColumnName("DistrictID");
            entity.Property(e => e.DistrictName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.DivisionCode)
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.DivisionId).HasColumnName("DivisionID");
            entity.Property(e => e.DivisionName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.InactivationNote)
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.PaurashavaName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.PsaCode)
                .IsRequired()
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.Status)
                .HasMaxLength(5)
                .IsUnicode(false);
            entity.Property(e => e.UpazilaCode)
                .IsRequired()
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.UpazilaId).HasColumnName("UpazilaID");
            entity.Property(e => e.UpazilaName)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.Upazila).WithMany(p => p.PauraShavaArea)
                .HasForeignKey(d => d.UpazilaId)
                .HasConstraintName("FK_PauraShavaArea_Upazila");
        });

        modelBuilder.Entity<PostOffice>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_PostCode");

            entity.ToTable("PostOffice", "ad");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("ID");
            entity.Property(e => e.CountryId).HasColumnName("CountryID");
            entity.Property(e => e.DistrictId).HasColumnName("DistrictID");
            entity.Property(e => e.DivisionId).HasColumnName("DivisionID");
            entity.Property(e => e.PostOffice1)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("PostOffice");
            entity.Property(e => e.UpazilaId).HasColumnName("UpazilaID");
        });

        modelBuilder.Entity<Privilege>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Privileg__3214EC275FDFEB57");

            entity.ToTable("Privilege", "sec");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("ID");
            entity.Property(e => e.Description)
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.Name)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Profession>(entity =>
        {
            entity.ToTable("Profession", "cl");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.ToTable("Role", "sec");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Description)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Name)
                .HasMaxLength(30)
                .IsUnicode(false);
        });

        modelBuilder.Entity<RolePrivilege>(entity =>
        {
            entity.HasKey(e => new { e.RoleId, e.PrivilegeId });

            entity.ToTable("RolePrivilege", "sec");

            entity.Property(e => e.RoleId).HasColumnName("RoleID");
            entity.Property(e => e.PrivilegeId).HasColumnName("PrivilegeID");

            entity.HasOne(d => d.Privilege).WithMany(p => p.RolePrivilege)
                .HasForeignKey(d => d.PrivilegeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RolePrivilege_Privilege");

            entity.HasOne(d => d.Role).WithMany(p => p.RolePrivilege)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RolePrivilege_Role");
        });

        modelBuilder.Entity<SavingsAccounts>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__SavingsA__3214EC2732C4941E");

            entity.ToTable("SavingsAccounts", "sav");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.AccountStatusId).HasColumnName("AccountStatusID");
            entity.Property(e => e.Balance).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.MemNoNavigation).WithMany(p => p.SavingsAccounts)
                .HasForeignKey(d => d.MemNo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_GeneralSavingsAccounts_Member");
        });

        modelBuilder.Entity<SavingsTransactionType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__SavingsT__3214EC27874FEF4A");

            entity.ToTable("SavingsTransactionType", "sav");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Name)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<SavingsTransactions>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_GeneralSavingsTransactions");

            entity.ToTable("SavingsTransactions", "sav");

            entity.Property(e => e.Id)
                .ValueGeneratedOnAdd()
                .HasColumnName("ID");
            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.BalanceAfter).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.SavingsAccountId).HasColumnName("SavingsAccountID");
            entity.Property(e => e.SavingsTransactionTypeId).HasColumnName("SavingsTransactionTypeID");

            entity.HasOne(d => d.IdNavigation).WithOne(p => p.SavingsTransactions)
                .HasForeignKey<SavingsTransactions>(d => d.Id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_GST_Account");
        });

        modelBuilder.Entity<Settings>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__settings__3214EC27F6BE67C8");

            entity.ToTable("settings", "sav");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("ID");
            entity.Property(e => e.GeneralInterestRate).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.MinimumBalance).HasColumnType("decimal(3, 0)");
        });

        modelBuilder.Entity<Union>(entity =>
        {
            entity.ToTable("Union", "ad");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("ID");
            entity.Property(e => e.AllInOne)
                .HasMaxLength(2000)
                .IsUnicode(false);
            entity.Property(e => e.DistrictCode)
                .IsRequired()
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.DistrictId).HasColumnName("DistrictID");
            entity.Property(e => e.DistrictName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.DivisionCode)
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.DivisionId).HasColumnName("DivisionID");
            entity.Property(e => e.DivisionName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.InactivationNote)
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.PauraShavaAreaId).HasColumnName("PauraShavaAreaID");
            entity.Property(e => e.PaurashavaAreaName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.PsaCode)
                .IsRequired()
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.Status)
                .HasMaxLength(5)
                .IsUnicode(false);
            entity.Property(e => e.UnionCode)
                .IsRequired()
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.UnionName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UpazilaCode)
                .IsRequired()
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.UpazilaId).HasColumnName("UpazilaID");
            entity.Property(e => e.UpazilaName)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.Upazila).WithMany(p => p.Union)
                .HasForeignKey(d => d.UpazilaId)
                .HasConstraintName("FK_Union_Upazila");
        });

        modelBuilder.Entity<Upazila>(entity =>
        {
            entity.ToTable("Upazila", "ad");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("ID");
            entity.Property(e => e.AccountDistrictId)
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength()
                .HasColumnName("Account_DistrictID");
            entity.Property(e => e.AccountUpazilaId)
                .HasMaxLength(3)
                .IsUnicode(false)
                .IsFixedLength()
                .HasColumnName("Account_UpazilaID");
            entity.Property(e => e.AllInOne)
                .HasMaxLength(2000)
                .IsUnicode(false);
            entity.Property(e => e.CountryId).HasColumnName("CountryID");
            entity.Property(e => e.CurrentAccountCode)
                .HasMaxLength(5)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.DistrictCode)
                .IsRequired()
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.DistrictId).HasColumnName("DistrictID");
            entity.Property(e => e.DistrictName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.DivisionCode)
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.DivisionId).HasColumnName("DivisionID");
            entity.Property(e => e.DivisionName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.HrDistrictId)
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength()
                .HasColumnName("HR_DistrictID");
            entity.Property(e => e.HrDivisionId)
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength()
                .HasColumnName("HR_DivisionID");
            entity.Property(e => e.HrUpazilaId)
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength()
                .HasColumnName("HR_UpazilaID");
            entity.Property(e => e.HrUpazilaId2)
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength()
                .HasColumnName("HR_UpazilaID2");
            entity.Property(e => e.HrUpazilaId3)
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength()
                .HasColumnName("HR_UpazilaID3");
            entity.Property(e => e.HrUpazilaId4)
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength()
                .HasColumnName("HR_UpazilaID4");
            entity.Property(e => e.InactivationNote)
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.LatOld).HasColumnName("Lat_Old");
            entity.Property(e => e.LongOld).HasColumnName("Long_Old");
            entity.Property(e => e.Status)
                .HasMaxLength(5)
                .IsUnicode(false);
            entity.Property(e => e.UpazilaCode)
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.UpazilaName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.District).WithMany(p => p.Upazila)
                .HasForeignKey(d => d.DistrictId)
                .HasConstraintName("FK_Upazila_District");
        });

        modelBuilder.Entity<Users>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Users__3214EC27E1007C4D");

            entity.ToTable("Users", "sec");

            entity.HasIndex(e => e.EmployeeId, "IX_Users").IsUnique();

            entity.HasIndex(e => e.UserName, "IX_Users_1").IsUnique();

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("ID");
            entity.Property(e => e.EffectiveDate).HasColumnType("smalldatetime");
            entity.Property(e => e.EmployeeId).HasColumnName("EmployeeID");
            entity.Property(e => e.Password).HasMaxLength(50);
            entity.Property(e => e.RoleId).HasColumnName("RoleID");
            entity.Property(e => e.SetDate).HasColumnType("smalldatetime");
            entity.Property(e => e.UserId).HasColumnName("UserID");
            entity.Property(e => e.UserName)
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Village>(entity =>
        {
            entity.ToTable("Village", "ad");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("ID");
            entity.Property(e => e.AllInOne)
                .HasMaxLength(2000)
                .IsUnicode(false);
            entity.Property(e => e.DistrictCode)
                .IsRequired()
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.DistrictId).HasColumnName("DistrictID");
            entity.Property(e => e.DistrictName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.DivisionCode)
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.DivisionId).HasColumnName("DivisionID");
            entity.Property(e => e.DivisionName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.MauzaCode)
                .IsRequired()
                .HasMaxLength(3)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.MauzaId).HasColumnName("MauzaID");
            entity.Property(e => e.MauzaName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.PaurashavaAreaId).HasColumnName("PaurashavaAreaID");
            entity.Property(e => e.PaurashavaName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.PsaCode)
                .IsRequired()
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.Status)
                .HasMaxLength(5)
                .IsUnicode(false);
            entity.Property(e => e.UnionCode)
                .IsRequired()
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.UnionId).HasColumnName("UnionID");
            entity.Property(e => e.UnionName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UpazilaCode)
                .IsRequired()
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.UpazilaId).HasColumnName("UpazilaID");
            entity.Property(e => e.UpazilaName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.VillageCode)
                .IsRequired()
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.VillageName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.Mauza).WithMany(p => p.Village)
                .HasForeignKey(d => d.MauzaId)
                .HasConstraintName("FK_Village_Mauza");
        });

        modelBuilder.Entity<Village2>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("Village2", "ad");

            entity.Property(e => e.Id).ValueGeneratedOnAdd();
            entity.Property(e => e.Id2).HasColumnName("ID2");
            entity.Property(e => e.VillageName).HasMaxLength(50);
            entity.Property(e => e.VillageNameBang).HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}